version: '3.8'
services: # Defines containers (services) your application needs.
  linkly-1:
    build: . # Docker will build an image using the Dockerfile in the current directory (.).
    volumes:
      - .:/srv/linkly
      - /srv/linkly/node_modules  # Avoid overwriting node_modules
    command: npm run dev
    ports: 
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - SERVER_TYPE=main
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}
      - REDIS_DB_URL=${REDIS_DB_URL}
      - INSTANCE_NAME=linkly-1
    mem_limit: 100m  # Limit to 100MB
    cpus: "0.2"   # Limit to 20% of one CPU
    depends_on:
      - nginx
      - postgres
      - redis
    networks:
      - linkly-net
  # linkly-2:
  #   build: . # Docker will build an image using the Dockerfile in the current directory (.).
  #   ports: 
  #     - "3001:3000"
  #   environment:
  #     - PORT=${PORT}
  #     - NODE_ENV=${NODE_ENV}
  #     - POSTGRES_DB_URL=${POSTGRES_DB_URL}
  #     - REDIS_DB_URL=${REDIS_DB_URL}
  #     - INSTANCE_NAME=linkly-2
  #   depends_on:
  #     - nginx
  #     - postgres
  #     - redis
  #   networks:
  #     - linkly-net

  nginx:
    build: ../nginx
    restart: always # Ensures that if the container crashes, it will automatically restart.
    ports:
      - "5000:80"
    networks:
      - linkly-net
  
  postgres:
    image: postgres:15
    restart: always # Ensures that if the container crashes, it will automatically restart.
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data # Uses a named volume (pgdata) to persist PostgreSQL data outside the container.
    networks:
      - linkly-net

  redis:
    image: redis:7
    restart: always
    volumes:
      - ./docker-volumes/redisdata:/data
    networks:
      - linkly-net

# Declares a named volume called pgdata.
# It will store PostgreSQL data persistently outside the container lifecycle.
volumes:
  pgdata:
  redisdata:

# Declares a custom bridge network called linkly-net.
# This isolates your services from other containers on your system.
# Enables DNS-style service discovery (e.g., postgres and redis as hostnames).
networks:
  linkly-net:
    driver: bridge




