name: Build and Push to Docker Hub
on:
  push:
    branches: 
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest # This machine comes pre-installed with Docker and other common tools.
    steps:
      - name: Debug partial secret
        run: echo "Token ${DOCKERHUB_TOKEN:0:4}****"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # This step checks out the latest code from your GitHub repo into the workflow's VM.
      # It allows the next steps (like Docker build) to access your source files.
      - name: Checkout Code
        uses: actions/checkout@v3

      # Sets up Docker Buildx, a modern builder from Docker 
      # Required for docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logs in to Docker Hub using your GitHub Secrets (safe and secure).
      # This is needed to push the image after it’s built.
      # The secrets are injected securely at runtime — not exposed in logs.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds your Docker image using the Dockerfile found in context: . (root folder).
      # push: true means it will push the built image to Docker Hub after building.
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gabhishek/linkly:latest

env:
  ACTIONS_STEP_DEBUG: true

